/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.0-dev1
 *
 * Project: 'microspeech.Release+MIMXRT1064' 
 * Target:  'Release+MIMXRT1064' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* tensorflow::Machine Learning:TensorFlow:Kernel&CMSIS-NN@1.22.5-rc4 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */
